version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    image: airflow-custom:2.10.2-python3.10
    container_name: airflow_webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "5_T23pT0u8dAOUYAiyEXU2E-l3dATTKDYMUH5zytkJ0="
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: >
      bash -c "
      echo 'Waiting for Postgres...' &&
      sleep 10 &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com || true &&
      airflow webserver
      "
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pipelines:/opt/airflow/pipelines
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

  airflow-scheduler:
    build: .
    image: airflow-custom:2.10.2-python3.10
    container_name: airflow_scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "5_T23pT0u8dAOUYAiyEXU2E-l3dATTKDYMUH5zytkJ0="
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: >
      bash -c "
      echo 'Waiting for Postgres...' &&
      sleep 10 &&
      airflow db migrate &&
      airflow scheduler
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pipelines:/opt/airflow/pipelines
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark_bronze
    user: root
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/spark/work-dir
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - .:/opt/spark/work-dir
      - spark_ivy_cache:/home/spark/.ivy2
    working_dir: /opt/spark/work-dir
    command: tail -f /dev/null



volumes:
  postgres_data:
  spark_ivy_cache:
